### ISSUE TITLE
NavigationListener.kt crashes when navigation is stopped

### ISSUE THREAD

**Issue by sharan-nyn** [3v1n0/GMapsParser#2]
I have a class which extends the NavigationListener.kt as follows:

  ```
class NavNotificationService : NavigationListener() {
      override fun onCreate() {
          enabled = true
          super.onCreate()
      }
  
      override fun onNavigationNotificationRemoved(navNotification: NavigationNotification) {
          val intent = Intent(NavigationService.NAVDATA_REMOVED)
          sendBroadcast(intent)
          super.onNavigationNotificationRemoved(navNotification)
      }
  
      override fun onNavigationNotificationUpdated(navNotification: NavigationNotification) {
          val intent = Intent(NavigationService.NAVDATA_UPDATED)
          intent.putExtra(NAVIGATION_DATA, navNotification.navigationData)
          sendBroadcast(intent)
          super.onNavigationNotificationUpdated(navNotification)
      }
  }
```

This works fine and I get my notifications using a broadcast receiver in NavigationService which is a foreground service.

The problem happens when I stop navigation by stopping it in maps.
It crashes the NavigationListener. The logs are as follows:

```
    java.lang.NullPointerException
        at me.trevi.navparser.service.NavigationListener.onNotificationRemoved(NavigationListener.kt:168)
        at android.service.notification.NotificationListenerService.onNotificationRemoved(NotificationListenerService.java:419)
        at android.service.notification.NotificationListenerService.onNotificationRemoved(NotificationListenerService.java:445)
        at android.service.notification.NotificationListenerService.onNotificationRemoved(NotificationListenerService.java:458)
        at android.service.notification.NotificationListenerService$MyHandler.handleMessage(NotificationListenerService.java:2152)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7661)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:594)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

Is this a code bug or an issue with my implementation ?

**Comment by 3v1n0** [comment]
Definitely a bug.... I didn't get that but may be just something I didn't handle properly....

It's not clear to me why `mCurrentNotification` is null in https://github.com/3v1n0/GMapsParser/blob/master/navparser/src/main/java/me/trevi/navparser/service/NavigationListener.kt#L168 might be worth checking for it, can you maybe debug the library?

If you got an event for the navigation added it's quite weird that the notification is null... 
Do you get it when using the embedded example app?

**Comment by sharan-nyn** [comment]
I ran my app in debug mode with breakpoint at NavigationListener.kt:168.
It never had null value there and it won't crash.

The peculiar thing is the app crashes when I simply 'Run'. But does not crash in debugging mode 😕

**Comment by 3v1n0** [comment]
Mhmh, i expect a race then... Could be that the coroutine thread isn't doing what I'm expected is doing?

**Comment by sharan-nyn** [comment]
As for the embedded example app, I can't get it build in Android Studio.
I tried opening GMapsParser directory as a project as well as GMapsParser/app as a project in Android Studio. Both throw gradle errors when it starts syncing.

Attached gradle logs:
[GMapsParser-AppGradle.log](https://github.com/3v1n0/GMapsParser/files/5989451/GMapsParser-AppGradle.log)
[GMapsParserGradle.log](https://github.com/3v1n0/GMapsParser/files/5989452/GMapsParserGradle.log)

**Comment by sharan-nyn** [comment]
> Mhmh, i expect a race then... Could be that the coroutine thread isn't doing what I'm expected is doing?

Yes it must be a race condition.
As sometimes even in normal execution the crash does not happen. It is intermittent

**Comment by lohith8099** [comment]
I have the same issue too ...

 java.lang.NullPointerException
        at me.trevi.navparser.service.NavigationListener.onNotificationRemoved(NavigationListener.kt:168)
        at android.service.notification.NotificationListenerService.onNotificationRemoved(NotificationListenerService.java:420)
        at android.service.notification.NotificationListenerService.onNotificationRemoved(NotificationListenerService.java:446)
        at android.service.notification.NotificationListenerService.onNotificationRemoved(NotificationListenerService.java:459)
        at android.service.notification.NotificationListenerService$MyHandler.handleMessage(NotificationListenerService.java:2176)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:246)
        at android.app.ActivityThread.main(ActivityThread.java:8506)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)


Would be great if you can fix it atleast temporarily since our users are using our app while riding their motorcycles and when the navigation crashes, they have to stop take their gloves off and do the whole process again.

Other than this the library is kickass and i cant thank you enough for this..

**Comment by lohith8099** [comment]
And as per crashlytics this is our number 1 issue as of now ... I still use Java and wish I could have worked on it . Is there anything I can help you with ?

**Comment by 3v1n0** [comment]
I've added some more checks on the callback, hopefully should not crash anymore... It may happen only if the value isn't unset, unless something weird happens in the coroutine.

Let me know.

PS: In what project are you using this?
